services:
  frontend:
    image: agnibhu369/food-delivery-frontend:1
    init: true
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      - backend
  admin:
    image: agnibhu369/food-delivery-admin:1
    init: true
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: agnibhu369/food-delivery-backend:1
    init: true
    ports:
      - 4000:4000
    restart: unless-stopped